/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LeCabinetRouteImport } from './routes/le-cabinet'
import { Route as ExpertisesRouteImport } from './routes/expertises'
import { Route as ExpertiseComptableRouteImport } from './routes/expertise-comptable'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConseilRouteImport } from './routes/conseil'
import { Route as AuditCommissariatAuxComptesRouteImport } from './routes/audit-commissariat-aux-comptes'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LeCabinetRoute = LeCabinetRouteImport.update({
  id: '/le-cabinet',
  path: '/le-cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertisesRoute = ExpertisesRouteImport.update({
  id: '/expertises',
  path: '/expertises',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseComptableRoute = ExpertiseComptableRouteImport.update({
  id: '/expertise-comptable',
  path: '/expertise-comptable',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilRoute = ConseilRouteImport.update({
  id: '/conseil',
  path: '/conseil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditCommissariatAuxComptesRoute =
  AuditCommissariatAuxComptesRouteImport.update({
    id: '/audit-commissariat-aux-comptes',
    path: '/audit-commissariat-aux-comptes',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-commissariat-aux-comptes': typeof AuditCommissariatAuxComptesRoute
  '/conseil': typeof ConseilRoute
  '/contact': typeof ContactRoute
  '/expertise-comptable': typeof ExpertiseComptableRoute
  '/expertises': typeof ExpertisesRoute
  '/le-cabinet': typeof LeCabinetRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-commissariat-aux-comptes': typeof AuditCommissariatAuxComptesRoute
  '/conseil': typeof ConseilRoute
  '/contact': typeof ContactRoute
  '/expertise-comptable': typeof ExpertiseComptableRoute
  '/expertises': typeof ExpertisesRoute
  '/le-cabinet': typeof LeCabinetRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-commissariat-aux-comptes': typeof AuditCommissariatAuxComptesRoute
  '/conseil': typeof ConseilRoute
  '/contact': typeof ContactRoute
  '/expertise-comptable': typeof ExpertiseComptableRoute
  '/expertises': typeof ExpertisesRoute
  '/le-cabinet': typeof LeCabinetRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-commissariat-aux-comptes'
    | '/conseil'
    | '/contact'
    | '/expertise-comptable'
    | '/expertises'
    | '/le-cabinet'
    | '/mentions-legales'
    | '/robots.txt'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-commissariat-aux-comptes'
    | '/conseil'
    | '/contact'
    | '/expertise-comptable'
    | '/expertises'
    | '/le-cabinet'
    | '/mentions-legales'
    | '/robots.txt'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/audit-commissariat-aux-comptes'
    | '/conseil'
    | '/contact'
    | '/expertise-comptable'
    | '/expertises'
    | '/le-cabinet'
    | '/mentions-legales'
    | '/robots.txt'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditCommissariatAuxComptesRoute: typeof AuditCommissariatAuxComptesRoute
  ConseilRoute: typeof ConseilRoute
  ContactRoute: typeof ContactRoute
  ExpertiseComptableRoute: typeof ExpertiseComptableRoute
  ExpertisesRoute: typeof ExpertisesRoute
  LeCabinetRoute: typeof LeCabinetRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/le-cabinet': {
      id: '/le-cabinet'
      path: '/le-cabinet'
      fullPath: '/le-cabinet'
      preLoaderRoute: typeof LeCabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertises': {
      id: '/expertises'
      path: '/expertises'
      fullPath: '/expertises'
      preLoaderRoute: typeof ExpertisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise-comptable': {
      id: '/expertise-comptable'
      path: '/expertise-comptable'
      fullPath: '/expertise-comptable'
      preLoaderRoute: typeof ExpertiseComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseil': {
      id: '/conseil'
      path: '/conseil'
      fullPath: '/conseil'
      preLoaderRoute: typeof ConseilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-commissariat-aux-comptes': {
      id: '/audit-commissariat-aux-comptes'
      path: '/audit-commissariat-aux-comptes'
      fullPath: '/audit-commissariat-aux-comptes'
      preLoaderRoute: typeof AuditCommissariatAuxComptesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditCommissariatAuxComptesRoute: AuditCommissariatAuxComptesRoute,
  ConseilRoute: ConseilRoute,
  ContactRoute: ContactRoute,
  ExpertiseComptableRoute: ExpertiseComptableRoute,
  ExpertisesRoute: ExpertisesRoute,
  LeCabinetRoute: LeCabinetRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
